hpo_lower_bound: 5
hpo_upper_bound: 15
lirical_yaml_template: data/template.yaml
# lirical_data_path: data/
lirical_data_path: /igm/home/rsrxs003/rnb/input/BL-173/data_dir
lirical_mindiff: 10000
gene_info: data/Homo_sapiens_gene_info.tsv
moi_db: data/moi.csv
pheno_score_source: data/pheno_scores_.csv
# pheno_score_source: data/clinphen_pheno_scores.csv
# pheno_score_source: /igm/home/rsrxs003/rnb/input/BL-186/original_ic.csv
# pheno_score_source: /igm/home/rsrxs003/rnb/input/BL-186/deid_ic.csv
pheno_score: IC
max_population_frequency: 0.01
phenoLR_scalar: 1
genoLR_scalar: 3.6
moiLR_scalar: 6.8
# genoLR_scalar: 1
# moiLR_scalar: 0
# diagnostic_source: data/ddd_diagnostic.xlsx
# diagnostic_source: data/rgs_diagnostic.xlsx
diagnostic_source: data/wes_diagnostic.xlsx
# diagnostic_source: /igm/home/rsrxs003/rnb/input/BL-186/deid_diagnostic.xlsx
# comparator_results: /igm/home/rsrxs003/rnb/output/BL-173/clinician_inputs/cavalri
# comparator_results: /igm/home/rsrxs003/rnb/output/BL-173/clinician_inputs
plot_label: ClinPhen
comparator_plot_label: Clinician