## DEPENDENCIES ##
annovar_scripts: /igm/home/rsrxs003/annovar
annovar_db: /igm/projects/CAVaLRi/dependencies/human_db
reference_path: dependencies/hg38.fa
# common_variants: data/WES_common_variants.csv
mutpredindel: dependencies/mutpredindel
mutpredindel_MCR: dependencies/mutpred-indel-mcr

## DATA TABLES ##
gene_info: dependencies/Homo_sapiens.gene_info
hpo: dependencies/hp.obo
hpoa: dependencies/phenotype.hpoa
phenotype_gene: dependencies/phenotype_to_genes.txt
mim2gene: dependencies/mim2gene_medgen
pheno_score_source: data/HPO_with_gene_IC.csv
pheno_score: IC
gnomadSV_version: 2.1

## CAVaLRi SETTINGS ##
run_mutpredindel: False
dbNSFP_score: MetaRNN_score
genome_build: hg38 
hpo_upper_bound: 19
pheno_root_penalty: 1
phenoLR_scalar: 1
genoLR_scalar: 2.1310546875
moiLR_scalar: 4.9615234375

## PATHOGENICITY FILTERS ##
snv_threshold: 0.5
spliceai_threshold: 0.5
mutpredindel_threshold: 0.5
cnvoyant_threshold: 0.5

## VARIANT FILTERING SETTINGS ##
gnomAD_popmax: 0.01
quality_minimum: 1
depth_minimum: 1

## BANDWIDTH SETTINGS ##
cores: 1
