## DEPENDENCIES ##
annovar_scripts: dependencies/annovar
annovar_db: dependencies/human_db
reference_path: dependencies/hg38.fa
# common_variants: data/DDD_common_variants.csv
common_variants: /data/WES_common_variants.csv
mutpredindel: /igm/home/rsrxs003/mutpred-indel/mutpredindel/
muptredindel_MCR: /igm/home/rsrxs003/mutpred-indel/mutpredindel/MCR2/v91/

## DATA TABLES ##
gene_info: dependencies/Homo_sapiens.gene_info
hpo: dependencies/hp.obo
hpoa: dependencies/phenotype.hpoa
phenotype_gene: dependencies/phenotype_to_genes.txt
mim2gene: dependencies/mim2gene_medgen
pheno_score_source: data/HPO_with_gene_IC.csv
pheno_score: IC

## CAVaLRi SETTINGS ##
run_mutpredindel: False
dbNSFP_score: MetaRNN_score
genome_build: hg38 
hpo_upper_bound: 19
pheno_root_penalty: 1
phenoLR_scalar: 1
genoLR_scalar: 2.2914306640625
moiLR_scalar: 3.6929443359375

## PATHOGENICITY FILTERS ##
snv_threshold: 0.5
spliceai_threshold: 0.5
mutpredindel_threshold: 0.5

## VARIANT FILTERING SETTINGS ##
gnomAD_popmax: 0.01
quality_minimum: 1
depth_minimum: 1

## BANDWIDTH SETTINGS ##
cores: 1
