## DEPENDICIES ##
annovar_scripts: dependencies/annovar
annovar_db: dependencies/human_db
exomiser_data: /igm/projects/exomiser/exomiser-cli-13.1.0/data/2209_hg38
lirical_executable: dependencies/LIRICAL.jar
lirical_data_path: dependencies/lirical_data
lirical_yaml_template: data/template.yaml
reference_path: dependencies/hg38.fa

## DATA TABLES ##
gene_info: data/Homo_sapiens_gene_info.tsv
moi_db: data/moi.csv
pheno_score_source: data/HPO_with_gene_IC.csv

## CAVaLRi SETTINGS ##
genome_build: hg38 
hpo_lower_bound: 5
hpo_upper_bound: 15
pheno_score: IC
phenoLR_scalar: 1
genoLR_scalar: 3.6
moiLR_scalar: 6.8

## PLOT SETTINGS ##
plot_label: Clinician
comparator_plot_label: ClinPhen

## VARIANT FILTERING SETTINGS ##
gnomAD_popmax: 0.005
quality_minimum: 200

## BANDWIDTH SETTINGS ##
cores: 50
