## DEPENDENCIES ##
annovar_scripts: /Users/rsrxs003/projects/annovar
annovar_db: /Users/rsrxs003/projects/CAVaLRi/dependencies
reference_path: /Users/rsrxs003/projects/CAVaLRi/dependencies/hg38.fa
# common_variants: /Users/rsrxs003/projects/CAVaLRi/data/common_variants.csv
mutpredindel: /Users/rsrxs003/projects/CAVaLRi/dependencies/mutpredindel
muptredindel_MCR: /Users/rsrxs003/projects/CAVaLRi/dependencies/mutpred-indel-mcr

## DATA TABLES ##
gene_info: /Users/rsrxs003/projects/CAVaLRi/dependencies/Homo_sapiens.gene_info
hpo: /Users/rsrxs003/projects/CAVaLRi/dependencies/hp.obo
hpoa: /Users/rsrxs003/projects/CAVaLRi/dependencies/phenotype.hpoa
phenotype_gene: /Users/rsrxs003/projects/CAVaLRi/dependencies/phenotype_to_genes.txt
mim2gene: /Users/rsrxs003/projects/CAVaLRi/dependencies/mim2gene_medgen
pheno_score_source: /Users/rsrxs003/projects/CAVaLRi/data/HPO_with_gene_IC.csv
pheno_score: IC

## CAVaLRi SETTINGS ##
run_mutpredindel: False
dbNSFP_score: MetaRNN_score
genome_build: hg38 
hpo_upper_bound: 19
pheno_root_penalty: 1
phenoLR_scalar: 1
genoLR_scalar: 2.2914306640625
moiLR_scalar: 3.6929443359375

## PATHOGENICITY FILTERS ##
snv_threshold: 0.5
spliceai_threshold: 0.5
mutpredindel_threshold: 0.5

## VARIANT FILTERING SETTINGS ##
gnomAD_popmax: 0.01
quality_minimum: 1
depth_minimum: 1

## BANDWIDTH SETTINGS ##
cores: 1
