name: cavalri_3.6
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.6.5
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - scipy
  - scikit-learn
  - pyvcf
  - obonet
  - tqdm
  - matplotlib
  - seaborn
  - spliceai
