name: cavalri
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10.8
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - scipy
  - scikit-learn
  - pyvcf
  - obonet
  - tqdm
  - matplotlib
  - seaborn
  - spliceai
  - gsl=2.5
  - bcftools
  - tabix