name: cavalri
channels:
  - conda-forge
  - bioconda
  - defaults  
dependencies:
  - python=3.10.8
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - scipy
  - scikit-learn
  - pyvcf3
  - obonet
  - tqdm
  - matplotlib
  - seaborn
  - spliceai
  - gsl
  - bcftools
  - tabix
  - samtools
  - pysam
  - htslib