import sys
import os
conda_bin = os.path.join(sys.exec_prefix, 'bin')

# Get configuration settings
configfile: "config.yaml"
shell.prefix(f'export PATH={conda_bin}:$PATH')
# ; mamba activate cavalri_3.6;

# Set up a temp folder to store pickles
temp_dir = config['tmp_dir']

# Define cases
CASES, = glob_wildcards(os.path.join(temp_dir, "{case}.pickle"))
CASES = [c for c in CASES if c.find('.full') == -1]

rule all:
    input:
        expand(os.path.join(temp_dir, "{case}.full.pickle"), case = CASES)


rule run_case:
    input:
        os.path.join(temp_dir, "{case}.pickle")
    params:
        script = os.path.abspath('scripts/run_case.py')
    output:
        os.path.join(temp_dir, "{case}.full.pickle")
    shell:
        'python {params.script} --input {input} -o {output}'